<script src="{{ asset('assets/js/jquery.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/js/fontawesome.min.js') }}"></script>
<script src="{{ asset('assets/js/editors.js') }}"></script>
<script src="{{ asset('assets/js/admin/openNav.js') }}"></script>
<script src="{{ asset('assets/js/admin/add_project.js') }}"></script>
<script src="{{ asset('assets/js/admin/uploadImages.js') }}"></script>
<script src="{{ asset('assets/js/slick.min.js') }}"></script>
<script src="{{ asset('assets/js/admin/delete_project.js') }}"></script>
{{-- <script src="{{ asset('assets/js/app.js') }}"></script> --}}
